services:
  - type: web
    name: flightops-companion
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: AISWEB_API_KEY
        sync: false
      - key: AISWEB_API_PASS
        sync: false
